(function(){"use strict";globalThis.__callMap||(globalThis.__callMap={});const l=globalThis.__callMap;function f(t,n){l[t]||(l[t]=!0,n())}function v(t){new MutationObserver(e=>{e.some(r=>!(r.type!=="childList"||r.addedNodes.length===0))&&t()}).observe(document,{childList:!0,subtree:!0})}globalThis.__overriddenMethods||(globalThis.__overriddenMethods={});const i=globalThis.__overriddenMethods;function a(t,n,e){const o=`${HTMLCanvasElement.prototype.constructor.name}.${String(n)}`;if(i[o])return;i[o]=!0;const r=t.prototype[n],c=new Proxy(r,{apply(T,p,b){return e.apply(p,[T,p,b])}});t.prototype[n]=c}function s(t=document){if(!t.querySelector("flutter-view"))return;t.querySelectorAll("flt-semantics-placeholder").forEach(c=>{c.click()});const e=t.querySelector("flt-glass-pane");if(!e||e.activated)return;e.activated=!0;const o=document.createElement("style");o.innerHTML=`
    flt-semantics {
      pointer-events: all !important;
    }
    flt-semantics-container {
      left: 0;
      top: 0;
    }
  `,o.id="flutter-override-styles",document.head.appendChild(o);const r=e.shadowRoot?.querySelector("flt-semantics-placeholder");r&&r.click()}function y(){a(Element,"attachShadow",(t,n,e)=>t.apply(n,[{...e[0],mode:"open"}]))}function h(t){if(!t)return"";const n={};return t.forEach(e=>{n[e.y]||(n[e.y]=[]),n[e.y]?.push(e)}),Object.values(n).forEach(e=>{e.sort((o,r)=>o.x-r.x)}),Object.entries(n).sort((e,o)=>e[0]-o[0]).map(([e,o])=>o.map(r=>r.text).join("")).join(`
`)}function d(t){t.textContent=h(t.texts)}function u(t,n,e,o){try{t.texts||(t.texts=[]),t.texts.push({text:n,x:e,y:o}),d(t)}catch(r){console.warn("Error in storing canvas text",r)}}function x(){a(CanvasRenderingContext2D,"fillText",(t,n,e)=>{t.apply(n,e),u(n.canvas,e[0],e[1],e[2])}),a(CanvasRenderingContext2D,"strokeText",(t,n,e)=>{t.apply(n,e),u(n.canvas,e[0],e[1],e[2])}),a(CanvasRenderingContext2D,"clearRect",(t,n,e)=>{t.apply(n,e);try{d(n.canvas),n.canvas.texts||(n.canvas.texts=[]),n.canvas.texts=n.canvas.texts.filter(o=>o.x<e[0]||o.x>e[0]+e[2]||o.y<e[1]||o.y>e[1]+e[3])}catch(o){console.warn("Error in clearRect",o)}}),f("override-canvas-innerText",()=>{Object.defineProperty(HTMLCanvasElement.prototype,"innerText",{get(){return this.textContent||""},set(t){this.textContent=t}})})}function M(){y(),x(),navigator.webdriver&&(s(),v(()=>{s()}))}M()})();
